'use strict';
(() => {
const D=window.ALSACE_DATA, KEY='alsace-atlas-v3', OLD='alsace-checklist-v2';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const empty=()=>({version:3,producers:[],wines:[],comparisons:[],explore:[],legacy:{checked:{},notes:{}}});
let state=empty(), tab='atlas',query='', region='all',kind='all',soil='all',coverage='all',wineStatus='all',producerRegion='all',producerStatus='all', storageWritable=true;
const sites=[...D.crus,...D.places], siteById=new Map(sites.map(s=>[s.id,s])), topicById=new Map(D.topics.map(t=>[t.id,t]));
const grapes=['Riesling','Gewurztraminer','Pinot Gris','Pinot Blanc','Auxerrois','Muscat','Sylvaner','Pinot Noir','Savagnin Rose','Chasselas','Chardonnay','Blend / other'];
const grapeTopics={'Riesling':'ries-base','Gewurztraminer':'gewurz-base','Pinot Gris':'pg-base','Pinot Blanc':'pb-base','Auxerrois':'aux-base','Muscat':'muscat-base','Sylvaner':'sylv-base','Savagnin Rose':'klevener','Chasselas':'chasselas','Chardonnay':'chardonnay'};
function notify(s){$('#dialog-notice').textContent=$('#editor').open?s:'';$('#notice').textContent=s;$('#notice').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').classList.remove('show'),6500)}
function save(){if(!storageWritable){notify('Browser storage is unavailable. Export a backup before leaving.');return false;}try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){notify('Could not save in this browser. Export a backup before leaving.');return false}}
function str(x,max=12000){if(x==null)return '';if(typeof x!=='string'||x.length>max)throw Error('Invalid text field');return x}
function strings(a){if(a==null)return [];if(!Array.isArray(a)||a.length>1000||a.some(x=>typeof x!=='string'||x.length>300))throw Error('Invalid selection');return [...new Set(a)]}
function safeUrl(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function legacyValid(x){if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Invalid legacy data');const out={checked:{},notes:{}};for(const key of ['checked','notes']){const m=x[key]||{};if(typeof m!=='object'||Array.isArray(m)||Object.keys(m).length>10000)throw Error('Invalid legacy data');for(const [k,v] of Object.entries(m)){if(['__proto__','constructor','prototype'].includes(k))throw Error('Invalid key');if(key==='notes')out.notes[k]=str(v);else if(v===1||v===true)out.checked[k]=1;else if(v!==0&&v!==false)throw Error('Invalid check');}}return out}
function validate(x){
 if(x?.version!==3)throw Error('Unsupported backup version');
 if(!Array.isArray(x.wines)||!Array.isArray(x.comparisons)||x.wines.length>10000||x.comparisons.length>10000)throw Error('Invalid backup');
 const out=empty();out.explore=strings(x.explore);out.legacy=legacyValid(x.legacy||{});
 if(x.producers!=null&&!Array.isArray(x.producers))throw Error('Invalid personal producers');
 if((x.producers||[]).length>10000)throw Error('Too many personal producers');
 out.producers=(x.producers||[]).map(p=>{if(!p||typeof p!=='object')throw Error('Invalid producer');const n={};for(const k of ['id','name','village','region','source','notes'])n[k]=str(p[k]);if(!n.id.startsWith('personal-')||!n.name.trim()||!n.village.trim()||!D.regions.some(r=>r.id===n.region)||n.source&&!safeUrl(n.source))throw Error('Invalid producer details');return n});
 if(new Set(out.producers.map(p=>p.id)).size!==out.producers.length)throw Error('Duplicate producer IDs');
 const producerIds=new Set([...window.ALSACE_PRODUCERS.entries,...out.producers].map(p=>p.id));
 const fields=['producerId','id','status','producer','cuvee','vintage','date','cellar','origin','originEvidence','grape','designation','site','region','venue','sugar','alcohol','vessel','notes','seller','country','url','price','checkedDate','availability','bottleRef'];
 out.wines=x.wines.map(w=>{if(!w||typeof w!=='object')throw Error('Invalid wine');const n={};fields.forEach(k=>n[k]=str(w[k]));n.topics=strings(w.topics);if(n.producerId&&!producerIds.has(n.producerId))throw Error('Unknown linked producer');if(!n.id||!n.producer||!['tasted','wishlist'].includes(n.status))throw Error('Invalid wine record');if(n.site&&!n.originEvidence.trim())throw Error('Site needs origin evidence');if(n.site&&!siteById.has(n.site))throw Error('Unknown site');if(n.topics.some(t=>!topicById.has(t)))throw Error('Unknown learning topic');if(n.url&&!safeUrl(n.url))throw Error('Invalid source URL');return n});
 const ids=new Set(out.wines.map(w=>w.id));if(ids.size!==out.wines.length)throw Error('Duplicate wine IDs');
 out.comparisons=x.comparisons.map(c=>{if(!c||typeof c!=='object')throw Error('Invalid comparison');const n={id:str(c.id),exercise:str(c.exercise),date:str(c.date),notes:str(c.notes),wines:strings(c.wines)};if(!n.id||!D.comparisons.some(e=>e.id===n.exercise)||!n.notes.trim()||n.wines.length<2||n.wines.some(id=>!out.wines.some(w=>w.id===id&&w.status==='tasted')))throw Error('Comparison needs two tasted records');return n});
 if(new Set(out.comparisons.map(c=>c.id)).size!==out.comparisons.length)throw Error('Duplicate comparison IDs');return out;
}
function tasted(){return state.wines.filter(w=>w.status==='tasted')}
function wineTopics(w){return [...new Set([...(w.topics||[]),...(grapeTopics[w.grape]?[grapeTopics[w.grape]]:[])])]}
function siteWines(id){return tasted().filter(w=>w.site===id)}
function topicWines(id){return tasted().filter(w=>wineTopics(w).includes(id))}
function want(id){return state.explore.includes(id)}
function source(id){const s=D.sources[id];return s?`<a class="source" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)} ↗</a>`:''}
function siteSource(s){return `<a class="source" href="${esc(s.source)}" target="_blank" rel="noopener">Reference ↗ · checked ${esc(s.reviewed)}</a>`}
function stats(){const ws=tasted();$('#stats').innerHTML=[['Tasting encounters',ws.length],['Grand Crus documented',new Set(ws.filter(w=>D.crus.some(s=>s.id===w.site)).map(w=>w.site)).size+' / 51'],['Learning topics encountered',new Set(ws.flatMap(wineTopics)).size],['Comparisons recorded',state.comparisons.length]].map(([l,n])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join('')}
function match(...a){return !query||norm(a.flat().join(' ')).includes(norm(query))}
function head(title,desc){return `<div class="view-head"><h2>${title}</h2><p>${desc}</p></div>`}
function options(a,current){return a.map(([v,n])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(n)}</option>`).join('')}
function selectFilter(id,label,a,current){return `<label>${label}<select id="${id}">${options(a,current)}</select></label>`}
function actions(id,site=false){return `<div class="actions"><button data-action="${site?'site-wine':'topic-wine'}" data-id="${esc(id)}">+ Link a wine</button><button data-action="explore" data-id="${esc(id)}" aria-pressed="${want(id)}">${want(id)?'✓ On my discovery list':'Explore later'}</button></div>`}
function atlas(){
 const soils=[...new Set(D.crus.map(c=>c.soil))].sort();
 let html=head('The geographical atlas','Follow the region north to south. All 51 Grands Crus, plus selected village and area entries. A site is documented only when you link a tasted wine to its verified grape origin.');
 html+=`<div class="filters">${selectFilter('region-filter','Area',[['all','All regions'],...D.regions.map(r=>[r.id,r.name])],region)}${selectFilter('kind-filter','Places',[['all','All places'],['Grand Cru','51 Grands Crus'],['Area / village','Areas & villages']],kind)}${selectFilter('soil-filter','Geology · source wording',[['all','All settings'],...soils.map(s=>[s,s])],soil)}${selectFilter('coverage-filter','Your exploration',[['all','All'],['seen','Wine documented'],['unseen','No wine documented'],['want','Explore later']],coverage)}</div>`;
 html+='<p class="small">Geology labels describe whole sites at reference scale; individual parcels can differ. “Wine documented” does not mean that you have visited or exhausted a place.</p>';
 let count=0;
 for(const r of D.regions){if(region!=='all'&&region!==r.id)continue;const list=sites.filter(s=>s.region===r.id&&(kind==='all'||s.kind===kind)&&(soil==='all'||s.soil===soil)&&match(s.name,s.village,s.soil,s.note,siteWines(s.id).map(w=>`${w.producer} ${w.cuvee} ${w.notes}`))&&(coverage==='all'||coverage==='seen'&&siteWines(s.id).length||coverage==='unseen'&&!siteWines(s.id).length||coverage==='want'&&want(s.id)));if(!list.length)continue;count+=list.length;
 html+=`<section class="region"><div class="eyeline">REGION ${r.number}</div><h3>${esc(r.name)} <span>${list.length} places shown</span></h3><p class="region-desc">${esc(r.description)}</p><div class="grid">${list.map(s=>{const n=siteWines(s.id).length;return `<article class="card"><div class="eyeline">${esc(s.kind)}</div><h4>${esc(s.name)}</h4><div><span class="pill ${n?'seen':''}">${n?`✓ ${n} tasting${n>1?'s':''}`:'Not yet documented'}</span>${want(s.id)?'<span class="pill want">Explore later</span>':''}</div>${s.note?`<p>${esc(s.note)}</p>`:`<dl class="facts"><dt>Village</dt><dd>${esc(s.village)}</dd><dt>Geology</dt><dd>${esc(s.soil)}</dd>${s.exposure?`<dt>Aspect</dt><dd>${esc(s.exposure)}</dd>`:''}${s.altitude?`<dt>Altitude</dt><dd>${esc(s.altitude)}</dd>`:''}</dl>`}${n?`<p>${siteWines(s.id).map(w=>esc(w.producer+' · '+w.cuvee+' '+w.vintage)).join('<br>')}</p>`:''}${siteSource(s)}${actions(s.id,true)}</article>`}).join('')}</div></section>`;
 }
 return html+(count?'':'<div class="empty">No places match these filters. Try another area or clear the search.</div>');
}
function learn(){let html=head('Learning axes','Build several kinds of understanding. A linked tasting records an encounter; comparisons and personal conclusions live in their own view.');
 html+='<div class="callout">One wine can contribute to several topics. Add only methods and origins you can verify; leave unknown details blank. Your observations come before any suggested flavour profile.</div>';
 let count=0;for(const a of D.axes){const ts=D.topics.filter(t=>t.axis===a.id&&match(t.name,t.detail,t.question,topicWines(t.id).map(w=>w.notes)));if(!ts.length)continue;count+=ts.length;html+=`<details class="axis" ${query||a.id==='grapes'?'open':''}><summary>${esc(a.title)} <small>${ts.filter(t=>topicWines(t.id).length).length} / ${ts.length} topics with a wine</small></summary><p class="region-desc">${esc(a.description)}</p><div class="grid">${ts.map(t=>`<article class="card"><h4>${esc(t.name)}</h4><span class="small">${topicWines(t.id).length} linked tasting encounters</span><p>${esc(t.detail)}</p><p class="question">Ask yourself: ${esc(t.question)}</p>${source(t.source)}${actions(t.id)}</article>`).join('')}</div></details>`}return html+(count?'':'<div class="empty">No matching learning topics.</div>')}
function producerMatch(...values){const text=norm(values.flat().join(' '));return norm(query).split(/\s+/).filter(Boolean).every(word=>text.includes(word))}
function allProducers(){return [...window.ALSACE_PRODUCERS.entries,...state.producers]}
function producerById(id){return allProducers().find(p=>p.id===id)}
function producerWines(id){return state.wines.filter(w=>w.producerId===id)}
function producers(){
 const meta=window.ALSACE_PRODUCERS;
 let html=head('Producers · north to south','Find a grower or cellar, then record its bottles in your wine journal. Locations describe the cellar, not the origin of every wine.');
 html+=`<details class="callout"><summary>Directory coverage · ${meta.entries.length} sourced cellar listings</summary><p>${meta.directoryCount} listings from the <a href="${esc(meta.source)}" target="_blank" rel="noopener">official Alsace Wine Route directory</a>, retrieved ${esc(meta.reviewed)}, cross-checked with <a href="${esc(meta.secondarySource)}" target="_blank" rel="noopener">Synvira’s independent-grower directory</a> (${meta.secondaryAdded} additional listings). Source names and multiple cellar or trading-name listings are retained; the count is not a count of unique companies. This visitor directory includes estates, cooperatives and multiple cellar locations; it is not a census of every wine grower. Add missing producers to your personal directory below. Entries are sorted by latitude within each area; entries without coordinates use the village latitude when available. Personal additions follow alphabetically.</p></details><div class="actions"><button class="primary" data-action="add-producer">+ Add a missing producer</button></div><div class="filters">${selectFilter('producer-region','Area',[['all','All regions'],...D.regions.map(r=>[r.id,r.name])],producerRegion)}${selectFilter('producer-status','Your bottles',[['all','All producers'],['tasted','With tasted wines'],['wishlist','With wishlist bottles'],['want','Explore later'],['personal','Personal additions']],producerStatus)}</div>`;
 let count=0;for(const r of D.regions){if(producerRegion!=='all'&&r.id!==producerRegion)continue;
 const ps=allProducers().filter(p=>p.region===r.id&&producerMatch(p.name,p.aliases||[],p.village,p.notes,producerWines(p.id).map(w=>`${w.cuvee} ${w.notes}`))&&(producerStatus==='all'||producerStatus==='tasted'&&producerWines(p.id).some(w=>w.status==='tasted')||producerStatus==='wishlist'&&producerWines(p.id).some(w=>w.status==='wishlist')||producerStatus==='want'&&want(p.id)||producerStatus==='personal'&&p.id.startsWith('personal-'))).sort((a,b)=>(b.lat||b.sortLat||0)-(a.lat||a.sortLat||0)||a.village.localeCompare(b.village)||a.name.localeCompare(b.name));
 if(!ps.length)continue;count+=ps.length;
 html+=`<section class="region"><div class="eyeline">REGION ${r.number}</div><h3>${esc(r.name)} <span>${ps.length} listings</span></h3><div class="grid">${ps.map(p=>{const ws=producerWines(p.id),t=ws.filter(w=>w.status==='tasted').length;return `<article class="card producer-card" data-producer="${esc(p.id)}"><div class="eyeline">${esc(p.village)}</div><h4>${esc(p.name)}</h4><div><span class="pill ${t?'seen':''}">${t} tasted · ${ws.length-t} wishlist</span>${want(p.id)?'<span class="pill want">Explore later</span>':''}</div>${p.aliases?.length?`<p class="small">Also listed as: ${esc([...new Set(p.aliases)].filter(n=>norm(n)!==norm(p.name)).join(' · '))}</p>`:''}${p.notes?`<p class="notes">${esc(p.notes)}</p>`:''}${ws.length?`<ul class="producer-bottles">${ws.map(w=>`<li><button data-action="edit-wine" data-id="${esc(w.id)}">${esc(w.cuvee||'Unnamed wine')} ${esc(w.vintage)} · ${w.status==='tasted'?'Tasted':'Wishlist'}</button></li>`).join('')}</ul>`:''}${p.additionalSources?.length?`<a class="source" href="${esc(p.additionalSources[0])}" target="_blank" rel="noopener">Synvira cross-reference ↗</a>`:''}${safeUrl(p.source)?`<a class="source" href="${esc(safeUrl(p.source))}" target="_blank" rel="noopener">${p.sourceKind==='route-directory'?'Wine Route directory':p.sourceKind==='synvira'?'Synvira directory':'Producer reference'} ↗</a>`:'<p class="small">Personal entry · location supplied by you</p>'}<div class="actions"><button data-action="producer-wine" data-id="${esc(p.id)}">+ Record a bottle</button><button data-action="producer-wishlist" data-id="${esc(p.id)}">+ Wishlist bottle</button><button data-action="explore" data-id="${esc(p.id)}" aria-pressed="${want(p.id)}">${want(p.id)?'✓ Explore later':'Explore later'}</button>${p.id.startsWith('personal-')?`<button data-action="edit-producer" data-id="${esc(p.id)}">Edit producer</button><button class="danger" data-action="delete-producer" data-id="${esc(p.id)}">Delete</button>`:''}</div></article>`}).join('')}</div></section>`;
 }return html+(count?'':'<div class="empty">No producers match. Clear the search or add a missing producer.</div>');
}
function openProducer(p={}){
 $('#dialog-title').textContent=p.id?'Edit personal producer':'Add a missing producer';
 $('#editor-body').innerHTML=`<form id="producer-form"><p class="small">Search the directory first to avoid duplicates. You can link existing journal records by editing their producer selection.</p><div class="form-grid">${field('producer','Producer name *',p.name)}${field('village','Cellar town / village *',p.village)}${select('region','Geographical area',D.regions.map(r=>[r.id,r.name]),p.region||D.regions[0].id,true)}${field('source','Producer website / reference',p.source,'url',true)}${area('notes','Personal producer notes',p.notes)}</div><div class="form-actions"><button type="button" data-action="close">Cancel</button><button class="primary" type="submit">Save producer</button></div></form>`;
 $('#producer-form').elements.village.required=true;$('#dialog-notice').textContent='';$('#editor').showModal();
 $('#producer-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),n={id:p.id||'personal-'+uid(),name:String(f.get('producer')).trim(),village:String(f.get('village')).trim(),region:String(f.get('region')),source:String(f.get('source')).trim(),notes:String(f.get('notes')).trim()};if(allProducers().some(x=>x.id!==n.id&&norm(x.name)===norm(n.name)&&norm(x.village)===norm(n.village))){notify('This producer and village already exist. Use the existing entry.');return}try{state=validate({...state,producers:p.id?state.producers.map(x=>x.id===p.id?n:x):[...state.producers,n]})}catch(err){notify(err.message);return}const saved=save();$('#editor').close();render();if(saved)notify('Producer saved. You can now record its bottles.');};
}

function journal(){const ws=state.wines.filter(w=>(wineStatus==='all'||w.status===wineStatus)&&match(Object.values(w),siteById.get(w.site)?.name,wineTopics(w).map(t=>topicById.get(t)?.name))).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('Your wine journal','Record a bottle once per tasting encounter and connect it to places and topics. Add a buying lead as a wishlist entry; it will not count as tasted.')+`<div class="filters">${selectFilter('wine-status','Show',[['all','Tastings & wishlist'],['tasted','Tasted'],['wishlist','Wishlist / buying leads']],wineStatus)}</div><p class="count-line">${ws.length} records shown</p>`+(ws.length?`<div class="journal-list">${ws.map(w=>`<article class="card wine-card"><div class="eyeline">${w.status==='tasted'?'TASTED':'WISHLIST'} · ${esc(w.date||'Date not recorded')}</div><h4>${esc(w.producer)}<br>${esc(w.cuvee)} ${esc(w.vintage)}</h4><p>${esc([w.grape,w.designation].filter(Boolean).join(' · '))}</p><dl class="facts"><dt>Cellar</dt><dd>${esc(w.cellar||'Not recorded')}</dd><dt>Grapes</dt><dd>${esc(siteById.get(w.site)?.name||w.origin||'Origin not confirmed')}</dd>${w.originEvidence?`<dt>Evidence</dt><dd>${esc(w.originEvidence)}</dd>`:''}</dl><div>${wineTopics(w).map(t=>`<span class="pill">${esc(topicById.get(t)?.name||t)}</span>`).join('')}</div>${w.notes?`<p class="notes">${esc(w.notes)}</p>`:''}${w.seller||w.price||w.availability?`<p>Buying lead: ${esc([w.seller,w.country,w.price,w.availability].filter(Boolean).join(' · '))}<br><span class="small">Last checked: ${esc(w.checkedDate||'Not verified')}. Stock can change.</span></p>`:''}${safeUrl(w.url)?`<a class="source" href="${esc(safeUrl(w.url))}" target="_blank" rel="noopener">Seller / technical sheet ↗</a>`:''}<div class="actions"><button data-action="edit-wine" data-id="${esc(w.id)}">Edit</button><button data-action="repeat-wine" data-id="${esc(w.id)}">Taste again</button><button class="danger" data-action="delete-wine" data-id="${esc(w.id)}">Delete</button></div></article>`).join('')}</div>`:'<div class="empty">No wines here yet. Record a tasting, or save a bottle you would like to find. Older checklist marks are preserved under Backup & history.</div>')}
function compare(){return head('Comparisons that teach','Choose two or more tasted journal records, then write what you noticed. The same bottle tasted on different occasions can have separate records. There is no prescribed “correct” flavour.')+`<div class="grid">${D.comparisons.filter(e=>match(e.name,e.question,state.comparisons.filter(c=>c.exercise===e.id).map(c=>c.notes))).map(e=>`<article class="card"><h4>${esc(e.name)}</h4><p>${esc(e.question)}</p><span class="small">${state.comparisons.filter(c=>c.exercise===e.id).length} recorded comparisons</span><div class="actions"><button data-action="new-comparison" data-id="${e.id}">+ Record comparison</button></div></article>`).join('')}</div><section class="region"><h3>Your observations</h3>${state.comparisons.length?state.comparisons.filter(c=>match(c.notes,D.comparisons.find(e=>e.id===c.exercise)?.name)).map(c=>`<article class="card"><h4>${esc(D.comparisons.find(e=>e.id===c.exercise)?.name)}</h4><p>${esc(c.date)}</p><p>${c.wines.map(id=>{const w=state.wines.find(x=>x.id===id);return esc(w?`${w.producer} ${w.cuvee} ${w.vintage}`:'Missing record')}).join(' ↔ ')}</p><p class="notes">${esc(c.notes)}</p><div class="actions"><button data-action="edit-comparison" data-id="${esc(c.id)}">Edit</button><button data-action="delete-comparison" data-id="${esc(c.id)}">Delete</button></div></article>`).join(''):'<p class="small">Your first comparison starts with two tasted records in the journal.</p>'}</section>`}
function backup(){const ids=[...new Set([...Object.keys(state.legacy.checked),...Object.keys(state.legacy.notes)])];return head('Keep your discoveries','Your journal stays in this browser. Export a backup to move it between devices or protect it before clearing browser data.')+`<div class="actions"><button class="primary" data-action="export">Export complete backup</button><button data-action="copy">Copy readable journal</button></div><label class="inline-file">Import a JSON backup (new atlas or old checklist)<input id="import-file" type="file" accept="application/json,.json"></label><p class="small">An atlas backup replaces the current atlas after confirmation. A legacy backup merges into the preserved history; it does not create fictional bottles or completed comparisons.</p><details class="axis" ${ids.length?'open':''}><summary>Preserved checklist history <small>${Object.keys(state.legacy.checked).length} old marks · ${Object.keys(state.legacy.notes).length} notes</small></summary><p class="small">Historical labels are shown as originally saved, not as updated reference facts. Existing marks and notes remain intact. To link an old tasting to the atlas, record its bottle details in the journal.</p>${ids.filter(id=>match(D.legacy[id]?.name,state.legacy.notes[id],id)).map(id=>`<div class="legacy-row"><strong>${state.legacy.checked[id]?'✓ ':''}${esc(D.legacy[id]?.name||id)}</strong><span class="small"> · ${esc(D.legacy[id]?.section||'Imported item')}</span>${state.legacy.notes[id]?`<p>${esc(state.legacy.notes[id])}</p>`:''}<button data-action="legacy-wine" data-id="${esc(id)}">Use note in a wine record</button></div>`).join('')||'<p>No previous checklist data found in this browser. You can import an old JSON backup.</p>'}</details><details class="axis"><summary>Sources & reading</summary><p>Site metadata was checked against CIVA pages on 12 September 2026. Whole-site descriptions simplify parcel variation. Learning questions are editorial, and buying availability is user-recorded rather than a stock promise.</p><ul class="source-list">${Object.values(D.sources).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)}</a></li>`).join('')}</ul></details>`}
function render(){stats();$('#view').innerHTML=({atlas,producers,learn,journal,compare,backup}[tab])();document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
function field(name,label,value='',type='text',full=false){return `<label class="${full?'full':''}">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${name==='producer'?'required':''} ${type==='number'?'min="0" step="any"':''}></label>`}
function select(name,label,values,value='',full=false){return `<label class="${full?'full':''}">${label}<select name="${name}">${options(values,value)}</select></label>`}
function area(name,label,v=''){return `<label class="full">${label}<textarea name="${name}">${esc(v)}</textarea></label>`}
function openWine(w={},isNew=false){
 $('#dialog-title').textContent=w.id&&!isNew?'Edit wine record':'Record a wine';
 const id=w.id&&!isNew?w.id:'';
 $('#editor-body').innerHTML=`<form id="wine-form" data-id="${esc(id)}"><div class="form-grid">${select('status','Record type',[['tasted','Tasted'],['wishlist','Wishlist / buying lead']],w.status||'tasted')}${field('date','Tasting date (or wishlist date)',w.date||today(),'date')}${select('producerId','Link to producer directory',[['','Unlinked / producer not in directory'],...allProducers().slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>[p.id,p.name+' · '+p.village])],w.producerId,true)}${field('producer','Producer as recorded on bottle *',w.producer)}${field('cuvee','Wine / cuvée',w.cuvee)}${field('vintage','Vintage / NV',w.vintage)}${select('grape','Grape (confirmed composition)',[['','Unknown / not recorded'],...grapes.map(g=>[g,g])],w.grape)}${field('designation','Designation as printed on label',w.designation)}${field('cellar','Producer / cellar location',w.cellar)}${select('site','Verified grape origin · atlas entry',[['','Unknown, mixed or another site'],...D.regions.flatMap(r=>sites.filter(s=>s.region===r.id).map(s=>[s.id,`${s.name} · ${s.kind}`]))],w.site,true)}${field('origin','Other / multiple grape origins',w.origin,'text',true)}${field('originEvidence','Origin evidence · label, producer or technical sheet',w.originEvidence,'text',true)}${field('venue','Where you tasted it',w.venue)}${field('bottleRef','Personal bottle reference (optional)',w.bottleRef)}${field('sugar','Residual sugar g/L · if known',w.sugar,'number')}${field('alcohol','Alcohol % · if known',w.alcohol,'number')}${field('vessel','Fermentation / ageing details · if known',w.vessel,'text',true)}${area('notes','Your observations, enjoyment & questions',w.notes)}</div><fieldset><legend>Additional learning topics</legend><p class="small">The selected grape links automatically to its basic topic. Select other topics only when supported by this wine; methods are not inferred from flavour.</p><div class="checks">${D.topics.map(t=>`<label class="check"><input type="checkbox" name="topics" value="${t.id}" ${(w.topics||[]).includes(t.id)?'checked':''}>${esc(t.name)}</label>`).join('')}</div></fieldset><details><summary>Buying lead / technical reference</summary><div class="form-grid">${field('seller','Seller / importer',w.seller)}${field('country','Country',w.country)}${field('price','Price & currency',w.price)}${field('checkedDate','Availability checked on',w.checkedDate,'date')}${select('availability','Availability',[['','Not verified'],['In stock when checked','In stock when checked'],['Previously available','Previously available'],['Out of stock when checked','Out of stock when checked'],['Ask seller','Ask seller']],w.availability)}${field('url','Seller / technical sheet URL',w.url,'url')}</div></details><div class="form-actions"><button type="button" data-action="close">Cancel</button><button class="primary" type="submit">Save wine record</button></div></form>`;$('#dialog-notice').textContent='';$('#editor').showModal();
 $('#wine-form').elements.producerId.onchange=e=>{const p=producerById(e.target.value);if(p){$('#wine-form').elements.producer.value=p.name;$('#wine-form').elements.cellar.value=p.village;}};
 $('#wine-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),wine={id:id||uid()};for(const [k,v] of f.entries())if(k!=='topics')wine[k]=String(v).trim();wine.topics=f.getAll('topics');if(wine.site&&!wine.originEvidence){notify('Add how you verified the grape origin, or leave the atlas entry unknown.');e.target.elements.originEvidence.focus();return}if(wine.site)wine.region=siteById.get(wine.site).region;
 if(id&&wine.status!=='tasted'&&state.comparisons.some(c=>c.wines.includes(id))){notify('This tasting belongs to a comparison. Remove that link before changing it to a wishlist entry.');return}
 const next={...state,wines:id?state.wines.map(w=>w.id===id?wine:w):[...state.wines,wine]};try{state=validate(next)}catch(err){notify(err.message);return}const saved=save();$('#editor').close();render();if(saved)notify('Wine saved. Its linked topics and place are updated.');});
}
function openComparison(exercise,id=''){const old=state.comparisons.find(c=>c.id===id)||{},e=D.comparisons.find(x=>x.id===exercise);$('#dialog-title').textContent=e.name;$('#editor-body').innerHTML=`<p>${esc(e.question)}</p><form id="comparison-form">${field('date','Date',old.date||today(),'date')}<fieldset><legend>Select at least two tasted records</legend><div class="checks">${tasted().map(w=>`<label class="check"><input type="checkbox" name="wines" value="${esc(w.id)}" ${(old.wines||[]).includes(w.id)?'checked':''}>${esc(w.producer+' · '+w.cuvee+' '+w.vintage+' · '+w.date)}</label>`).join('')||'<p>Add tasted wines to the journal first.</p>'}</div></fieldset>${area('notes','Your observations · what differed, what stayed similar, and possible confounders',old.notes)}<div class="form-actions"><button type="button" data-action="close">Cancel</button><button type="submit" class="primary">Save comparison</button></div></form>`;$('#dialog-notice').textContent='';$('#editor').showModal();$('#comparison-form').onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target),wines=f.getAll('wines');if(wines.length<2){notify('Choose at least two tasted journal records.');return}const notes=String(f.get('notes')).trim();if(!notes){notify('Add an observation before completing this comparison.');return}const c={id:id||uid(),exercise,date:String(f.get('date')),notes,wines};state.comparisons=id?state.comparisons.map(x=>x.id===id?c:x):[...state.comparisons,c];const saved=save();$('#editor').close();render();if(saved)notify('Comparison saved.');}}
function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`alsace-atlas-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function readable(){const history=[...new Set([...Object.keys(state.legacy.checked),...Object.keys(state.legacy.notes)])].map(id=>`${state.legacy.checked[id]?'✓ ':''}${D.legacy[id]?.name||id}\n${state.legacy.notes[id]||''}`);return ['ALSACE WINE JOURNAL',...state.wines.map(w=>`\n${w.status.toUpperCase()} · ${w.producer} — ${w.cuvee} ${w.vintage}\nDate: ${w.date}\nGrape origin: ${siteById.get(w.site)?.name||w.origin||'Unknown'}\n${w.notes||''}`),'\nPERSONAL PRODUCERS',...state.producers.map(p=>`${p.name} · ${p.village}\n${p.notes||''}\n${p.source||''}`),'\nCOMPARISONS',...state.comparisons.map(c=>`${D.comparisons.find(e=>e.id===c.exercise)?.name}\n${c.notes}`),'\nPRESERVED HISTORY',...history].join('\n')}
async function importFile(file){if(!file)return;if(file.size>10*1024*1024){notify('Backup is too large (maximum 10 MB).');return}try{const raw=JSON.parse(await file.text());let next;if(raw.version===3){next=validate(raw);if(!confirm('Replace this browser’s atlas with this backup? Export your current atlas first if you want to keep both.'))return}else if(raw.checked||raw.notes){const l=legacyValid(raw);next={...state,legacy:{checked:{...state.legacy.checked,...l.checked},notes:{...state.legacy.notes,...l.notes}}};if(!confirm('Merge these old checklist marks and notes into preserved history?'))return}else throw Error('Not an atlas or checklist backup');state=next;const saved=save();render();if(saved)notify('Backup imported successfully.')}catch(e){notify('Import rejected: '+e.message)}}
$('#search').oninput=e=>{query=e.target.value;render()};$('#add-wine').onclick=()=>openWine();$('#close-dialog').onclick=()=>$('#editor').close();
document.addEventListener('change',e=>{const v=e.target.value;switch(e.target.id){case 'producer-region':producerRegion=v;break;case 'producer-status':producerStatus=v;break;case 'region-filter':region=v;break;case 'kind-filter':kind=v;break;case 'soil-filter':soil=v;break;case 'coverage-filter':coverage=v;break;case 'wine-status':wineStatus=v;break;case 'import-file':importFile(e.target.files[0]);return;default:return}render()});
document.addEventListener('click',async e=>{
 const nav=e.target.closest('[data-tab]');if(nav){tab=nav.dataset.tab;query='';$('#search').value='';render();return}
 const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.id;
 switch(b.dataset.action){
 case 'add-producer':openProducer();break;
 case 'edit-producer':openProducer(producerById(id));break;
 case 'delete-producer':if(producerWines(id).length){notify('This producer has linked bottles. Unlink them in the journal before deleting the producer.');break}if(confirm('Delete this personal producer?')){state.producers=state.producers.filter(p=>p.id!==id);state.explore=state.explore.filter(x=>x!==id);save();render()}break;
 case 'producer-wine':case 'producer-wishlist':{const p=producerById(id);openWine({producerId:p.id,producer:p.name,cellar:p.village,status:b.dataset.action==='producer-wishlist'?'wishlist':'tasted'});break}
 case 'close':$('#editor').close();break;
 case 'site-wine':openWine({site:id});break;
 case 'topic-wine':openWine({topics:[id]});break;
 case 'edit-wine':openWine(state.wines.find(w=>w.id===id));break;
 case 'repeat-wine':{const w=state.wines.find(w=>w.id===id);openWine({...w,id:'',date:today(),notes:'',status:'tasted'},true);break}
 case 'legacy-wine':openWine({notes:state.legacy.notes[id]||'',topics:topicById.has(id)?[id]:[]});break;
 case 'explore':state.explore=want(id)?state.explore.filter(x=>x!==id):[...state.explore,id];save();render();break;
 case 'delete-wine':if(state.comparisons.some(c=>c.wines.includes(id))){notify('This wine is linked to a comparison. Edit or delete that comparison first.');break}if(confirm('Delete this wine record?')){state.wines=state.wines.filter(w=>w.id!==id);save();render()}break;
 case 'new-comparison':openComparison(id);break;
 case 'edit-comparison':openComparison(state.comparisons.find(c=>c.id===id).exercise,id);break;
 case 'delete-comparison':if(confirm('Delete this comparison?')){state.comparisons=state.comparisons.filter(c=>c.id!==id);save();render()}break;
 case 'export':download();break;
 case 'copy':try{await navigator.clipboard.writeText(readable());notify('Readable journal copied. Use Export for a restorable backup.')}catch{notify('Clipboard unavailable. Use Export complete backup instead.')}break;
 }
});
// Never overwrite the old key. Old marks are evidence of old actions, not fabricated tasting records.
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));else{const old=localStorage.getItem(OLD);if(old){state.legacy=legacyValid(JSON.parse(old));save();}}}catch(e){storageWritable=false;notify('Saved data could not be loaded. It has not been overwritten. Export or recover your browser data before continuing.');}
render();
// Listen for another tab’s saves without silently overwriting an open editor.
window.addEventListener('storage',e=>{if(e.key===KEY){storageWritable=false;notify('The journal changed in another tab. Reload before making further edits; saving is paused to protect those changes.');}});
})();
