const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined});
 const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 const counts=await page.evaluate(()=>{const d=window.ALSACE_DATA;return [d.crus.length,d.places.length,d.axes.length,d.topics.length,d.comparisons.length]});assert.deepEqual(counts,[51,21,11,95,12]);
 const original={checked:{'r-gneiss':1,'and-kastelberg':1,'custom-old':1},notes:{'v-andlau':'Original note <b>not HTML</b> & wine','custom-old':'Keep unknown IDs'}};
 await page.evaluate(x=>{localStorage.clear();localStorage.setItem('alsace-checklist-v2',JSON.stringify(x))},original);await page.reload();
 assert.equal(await page.locator('.card').count(),72);
 let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('alsace-atlas-v3')));
 assert.deepEqual(state.legacy,original);assert.equal(state.wines.length,0);
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('alsace-checklist-v2'))),original);
 await page.locator('[data-tab=backup]').click();assert.ok((await page.locator('#view').textContent()).includes('Original note <b>not HTML</b>'));
 await page.locator('[data-tab=atlas]').click();await page.locator('#search').fill('Frankstein');assert.equal(await page.locator('.card').count(),1);assert.ok((await page.locator('.facts').textContent()).includes('Granite'));
 await page.locator('[data-action=site-wine]').click();
 await page.locator('[name=producer]').fill('Sample <img src=x onerror=alert(1)>');await page.locator('[name=cuvee]').fill('Study bottle');await page.locator('[name=grape]').selectOption('Riesling');await page.locator('[name=notes]').fill('Citrus & tension');await page.locator('#wine-form button[type=submit]').click();assert.equal(await page.locator('#editor').evaluate(e=>e.open),true,'origin evidence required');
 await page.locator('[name=originEvidence]').fill('Producer technical sheet');await page.locator('[name=status]').selectOption('wishlist');await page.locator('#wine-form button[type=submit]').click();
 assert.ok((await page.locator('#stats').textContent()).includes('0 / 72'));
 await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.wine-card').count(),1);assert.equal(await page.locator('.wine-card img').count(),0);
 await page.locator('[data-action=edit-wine]').click();await page.locator('[name=status]').selectOption('tasted');await page.locator('#wine-form button[type=submit]').click();
 assert.ok((await page.locator('#stats').textContent()).includes('1 / 72'));
 await page.locator('[data-action=repeat-wine]').click();await page.locator('[name=notes]').fill('Next day: softer');await page.locator('#wine-form button[type=submit]').click();assert.equal(await page.locator('.wine-card').count(),2);
 await page.locator('[data-tab=compare]').click();await page.locator('[data-action=new-comparison][data-id=time-pair]').click();await page.locator('[name=wines]').first().check();await page.locator('[name=notes]').fill('The same bottle changed with air.');await page.locator('#comparison-form button[type=submit]').click();assert.equal(await page.locator('#editor').evaluate(e=>e.open),true);
 await page.locator('[name=wines]').nth(1).check();await page.locator('#comparison-form button[type=submit]').click();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('alsace-atlas-v3')));assert.equal(state.comparisons.length,1);
 await page.locator('[data-tab=journal]').click();await page.locator('[data-action=delete-wine]').first().click();assert.equal(await page.locator('.wine-card').count(),2,'linked wine protected');
 await page.reload();await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.wine-card').count(),2);await page.locator('#search').fill('softer');assert.equal(await page.locator('.wine-card').count(),1,'notes searchable');
 await page.locator('[data-tab=backup]').click();const downloadEvent=page.waitForEvent('download');await page.locator('[data-action=export]').click();const download=await downloadEvent;const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(backup.wines.length,2);assert.deepEqual(backup.legacy,original);
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.locator('[data-action=copy]').click();assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('Keep unknown IDs'),'unknown legacy notes in readable export');
 const before=await page.evaluate(()=>localStorage.getItem('alsace-atlas-v3'));
 await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:3,wines:[],comparisons:[{id:'bad',exercise:'time-pair',wines:['missing','another']}]}))});
 assert.equal(await page.evaluate(()=>localStorage.getItem('alsace-atlas-v3')),before,'invalid backup cannot mutate data');
 page.once('dialog',d=>d.accept());await page.locator('#import-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('successfully'));assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('alsace-atlas-v3'))),backup);
 await page.locator('[data-tab=atlas]').click();await page.locator('#kind-filter').selectOption('Grand Cru');assert.equal(await page.locator('.card').count(),51);await page.locator('#region-filter').selectOption('north');assert.equal(await page.locator('.card').count(),0);await page.locator('#region-filter').selectOption('all');await page.locator('#kind-filter').selectOption('all');
 fs.mkdirSync(path.join(__dirname,'../test-results'),{recursive:true});await page.evaluate(()=>{scrollTo(0,0);document.querySelector('#notice').classList.remove('show')});await page.screenshot({path:path.join(__dirname,'../test-results/desktop.png')});
 await page.setViewportSize({width:390,height:844});for(const t of ['atlas','learn','journal','compare','backup']){await page.locator(`[data-tab=${t}]`).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`mobile overflow: ${t}`)}await page.locator('[data-tab=atlas]').click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(__dirname,'../test-results/mobile.png')});
 await page.locator('#add-wine').click();assert.ok(await page.locator('#editor').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'mobile dialog overflow');await page.locator('#close-dialog').click();
 await page.evaluate(()=>localStorage.setItem('alsace-atlas-v3','corrupted original'));await page.reload();await page.locator('[data-action=explore]').first().click();assert.equal(await page.evaluate(()=>localStorage.getItem('alsace-atlas-v3')),'corrupted original','unreadable storage never overwritten');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: atlas integrity, migration, wishlist/tasted coverage, origin evidence, repeated tastings, comparisons, XSS-safe notes, persistence, search, backup round trip, invalid import and mobile layouts.');
})().catch(e=>{console.error(e);process.exit(1)});
