const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');
// Pre-existing v3 backups have neither personal producers nor producerId.
await page.evaluate(()=>{localStorage.setItem('alsace-atlas-v3',JSON.stringify({version:3,wines:[{id:'old',producer:'Existing bottle',status:'tasted',notes:'Keep me'}],comparisons:[],explore:[],legacy:{checked:{},notes:{}}}))});await page.reload();await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.wine-card').count(),1);
await page.locator('[data-tab=producers]').click();assert.equal(await page.locator('.producer-card').count(),771);
const integrity=await page.evaluate(()=>{const ps=window.ALSACE_PRODUCERS.entries;return new Set(ps.map(p=>p.id)).size===ps.length&&ps.every(p=>window.ALSACE_DATA.regions.some(r=>r.id===p.region)&&p.source.startsWith('https://'))});assert.ok(integrity);
await page.locator('#search').fill('Albert Boxler');assert.equal(await page.locator('.producer-card').count(),1,'search supports either name order');
await page.locator('#search').fill('BOXler');assert.ok(await page.locator('.producer-card').count()>=2);
await page.locator('#search').fill('Ostertag');const card=page.locator('.producer-card').filter({has:page.getByRole('heading',{name:'Domaine OSTERTAG',exact:true})});await card.locator('[data-action=producer-wine]').click();assert.equal(await page.locator('[name=producer]').inputValue(),'Domaine OSTERTAG');assert.equal(await page.locator('[name=cellar]').inputValue(),'Epfig');assert.equal(await page.locator('[name=site]').inputValue(),'');await page.locator('[name=cuvee]').fill('Riesling test');await page.locator('#wine-form button[type=submit]').click();assert.ok((await card.textContent()).includes('1 tasted'));
await card.locator('[data-action=producer-wishlist]').click();await page.locator('[name=cuvee]').fill('Future bottle');await page.locator('#wine-form button[type=submit]').click();assert.ok((await card.textContent()).includes('1 tasted · 1 wishlist'));await card.getByRole('button',{name:'Riesling test · Tasted',exact:true}).click();assert.equal(await page.locator('[name=cuvee]').inputValue(),'Riesling test');await page.locator('#close-dialog').click();
await page.locator('#search').fill('');await page.locator('[data-action=add-producer]').click();await page.locator('[name=producer]').fill('Personal <b>grower</b>');await page.locator('[name=village]').fill('Turckheim');await page.locator('[name=region]').selectOption('colmar');await page.locator('[name=notes]').fill('Saved grower notes');await page.locator('#producer-form button[type=submit]').click();await page.locator('#producer-status').selectOption('personal');assert.equal(await page.locator('.producer-card').count(),1);assert.equal(await page.locator('.producer-card b').count(),0);await page.locator('[data-action=producer-wine]').click();await page.locator('[name=cuvee]').fill('Personal bottle');await page.locator('#wine-form button[type=submit]').click();await page.locator('[data-action=delete-producer]').click();assert.equal(await page.locator('.producer-card').count(),1,'protect linked producer');
await page.locator('[data-tab=journal]').click();await page.locator('.wine-card').filter({hasText:'Existing bottle'}).locator('[data-action=edit-wine]').click();const personalId=await page.evaluate(()=>JSON.parse(localStorage.getItem('alsace-atlas-v3')).producers[0].id);await page.locator('[name=producerId]').selectOption(personalId);await page.locator('#wine-form button[type=submit]').click();
await page.locator('[data-tab=backup]').click();const evt=page.waitForEvent('download');await page.locator('[data-action=export]').click();const d=await evt;const backup=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(backup.producers.length,1);assert.equal(backup.wines.find(w=>w.id==='old').producerId,personalId);assert.equal(backup.wines.find(w=>w.id==='old').notes,'Keep me');page.once('dialog',d=>d.accept());await page.locator('#import-file').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('successfully'));await page.reload();await page.locator('[data-tab=producers]').click();await page.locator('#producer-status').selectOption('personal');assert.ok((await page.locator('.producer-card').textContent()).includes('2 tasted'));
const before=await page.evaluate(()=>localStorage.getItem('alsace-atlas-v3'));backup.producers[0].source='javascript:alert(1)';await page.locator('[data-tab=backup]').click();await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('rejected'));assert.equal(await page.evaluate(()=>localStorage.getItem('alsace-atlas-v3')),before);
await page.locator('[data-tab=producers]').click();await page.locator('#producer-status').selectOption('all');await page.locator('#producer-region').selectOption('central-bas');await page.evaluate(()=>{scrollTo(0,400);document.querySelector('#notice').classList.remove('show')});fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/producers-desktop.png'});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/producers-mobile.png'});await page.locator('[data-action=producer-wine]').first().click();assert.ok(await page.locator('#editor').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.deepEqual(errors,[]);await browser.close();console.log('PASS: producer directory, legacy v3 migration, bottle linking/editing, wishlist counts, custom producers, deletion protection, backups, unsafe imports, mobile layout.');
})().catch(e=>{console.error(e);process.exit(1)});
